development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:a5ad96a71f20c965fc3a415f45a1fd46@pike.redistogo.com:10639/
  channel_prefix: todo-tracker_production
